module.exports = [
  {
    date: "June 1",
    name: "Rent",
    amount: 1800,
    from: "Me",
    negative: true,
  },
  {
    date: "June 5",
    name: "Income",
    amount: 2400,
    from: "Pursuit",
    negative: false,
  },
  {
    date: "June 5",
    name: "Retirement",
    amount: 400,
    from: "Checking",
    negative: true,
  },
  {
    date: "June 6",
    name: "Lottery",
    amount: 5000,
    from: "New York State",
    negative: false,
  },
  {
    date: "June 10",
    name: "Dinner",
    amount: 110,
    from: "Carmines",
    negative: true,
  },
  {
    date: "June 10",
    name: "Movies",
    amount: 50,
    from: "Regal Cinemas",
    negative: true,
  },
  {
    date: "June 12",
    name: "Grocery",
    amount: 250,
    from: "Shoprite",
    negative: true,
  },
  {
    date: "June 13",
    name: "CashApp",
    amount: 65,
    from: "Mike",
    negative: false,
  },
  {
    date: "June 14",
    name: "Bills",
    amount: 565,
    from: "Gas Phone Internet Electric",
    negative: true,
  },
  {
    date: "June 15",
    name: "Computer",
    amount: 2300,
    from: "Apple",
    negative: true,
  },
];
